### ISSUE TITLE
Don't understand the stretch property

### ISSUE THREAD

**Issue by Fransebas** [DanFessler/react-panelgroup#33]
Hi, first of all, I really like your library thanks form making it!. But I have a problem, I don't understand how does the "weight" works when the `resize` property is `stretch`, Could you care to explain me?

**Comment by DanFessler** [comment]
Functionally it turns on flex-grow and flex-shrink for that panel, but I'm not sure how useful it is because it becomes controlled via pixel units internally either way.  I typically use a single stretch panel with the remaining panels being dynamic just so I can ensure my UI can fit any required resolution regardless of the min and max sizes I've set on them.
