### ISSUE TITLE
Snapping feature

### ISSUE THREAD

**Issue by mkulinski** [DanFessler/react-panelgroup#7]
Hello,

I'm trying add a snapping feature to react-panelgroup. So far I've tried to change the size of each panel object based on where it is, the container width and how many panels there are. But when I change the size it gets stuck in a never ending loop of updating.

Figured I'd come on here and see if you know of any projects that tried to add some kind of snapping or constraining feature to react-panelgroup?

Thanks,
Michael

**Comment by DanFessler** [comment]
This is something I've been meaning to add.  I haven't seen anyone else add it yet, so I'll probably give it a go today.  Curious what your intended snapping behavior is that you're looking for - Arbitrary snap positions, or just snapping to the min and max size?

**Comment by DanFessler** [comment]
Added experimental support for it.  You can supply an array of snap positions so you can have multiple per panel.  There are some edge cases which trigger a maximum call stack error that I need to work out, but it still works for the most part.  Feel free to contribute to make it better.

**Comment by mkulinski** [comment]
Hey Dan,

Thanks for getting back to me. My intention with the snap feature is to only allow the user to resize at a fixed interval of percentages based on the overall size of the panel group. So every panel group would only allow the user to have a panel either 15%, 25%, 50%, 75%. Something like that.

I haven't had a chance to play with your new addition, but I look forward to diving into it today.

**Comment by DanFessler** [comment]
Gotcha.  My implementation snaps to pixel positions rather than percentages.  Also it only snaps when you are close to the snap target (currently that margin is a hard coded constant, should be changed) - so it's a bit less heavy handed than what you're after.

I'll think a bit about how well your implementation makes sense for this project, but you might be able to take a look at the changes I made on this latest push to get an idea for how to implement it yourself.
